name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: pip install pyvcd

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential meson gperf flex desktop-file-utils libgtk-3-dev libbz2-dev libjudy-dev libgirepository1.0-dev libfst-dev libgtk-4-dev libgtk-4-dev systemd-coredump valgrind ccache gdb clangd  wmctrl fluxbox xvfb python3-pyatspi python3-xlib python3-gi at-spi2-core python3-pip xdotool

      - name: Install Python dependencies
        run: sudo /usr/bin/python3 -m pip install pyvcd --break

